package View;

import Controller.Gestor_Est;
import View.Util.Util;
import exs.logs.err.Log;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A.
 */
public class U_Reg_Ini extends javax.swing.JFrame {

    private Gestor_Est controller = null;

    public U_Reg_Ini() {
        initComponents();
        init();
        if (!controller.isUsable()) {
            setVisible(false);
            JOptionPane.showMessageDialog(null, "No se puede continuar con la ejecucion del programa...", "DB Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    private void init() {
        controller = Gestor_Est.getInstancia();
        setImages();
        l_id.setVisible(false);
        this.setTitle("Registro de Estudiantes - ExS");
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);
            l_ima.setIcon(new ImageIcon("img/front.jpg"));
            b_send.setIcon(new ImageIcon("img/b_send.png"));

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
    }

    private void send() {
        if (!l_id.isVisible() && !t_ced.getText().isEmpty()) {
            controller.setEst(t_ced.getText());
            t_ced.setText("");
            new U_Reg_Acep().setVisible(true);
        } else {
            //JOptionPane
        }
    }

    private void close() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_top = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        b_send = new javax.swing.JButton();
        l_ima = new javax.swing.JLabel();
        t_ced = new javax.swing.JTextField();
        l_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        setResizable(false);

        l_top.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_top.setText("Registro de Estudiantes");

        jSeparator1.setEnabled(false);

        b_send.setText("Matricular");
        b_send.setMaximumSize(new java.awt.Dimension(35, 10));
        b_send.setMinimumSize(new java.awt.Dimension(35, 10));
        b_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sendActionPerformed(evt);
            }
        });

        t_ced.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        t_ced.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_id(evt);
            }
        });

        l_id.setForeground(new java.awt.Color(153, 0, 0));
        l_id.setText("La identificación debe tener únicamente 9 dígitos ");

        jLabel1.setText("Ingrese su núnero de identifiación y presione el botón matricuar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(l_ima, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(l_id))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(t_ced, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_top)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_top)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_ima, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_send, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(t_ced))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sendActionPerformed
        send();
    }//GEN-LAST:event_b_sendActionPerformed

    private void key_id(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_id
        if(!t_ced.getText().isEmpty()){
            l_id.setVisible(!Util.checkIsNumber(t_ced.getText()) || !(t_ced.getText().length() < 10)  || !(t_ced.getText().length() > 8) );
        }else{
            l_id.setVisible(false);
        }
        
    }//GEN-LAST:event_key_id
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_id;
    private javax.swing.JLabel l_ima;
    private javax.swing.JLabel l_top;
    private javax.swing.JTextField t_ced;
    // End of variables declaration//GEN-END:variables
}
