package View;

import Controller.Gestor_Est;
import View.Util.Util;
import exs.logs.err.Log;
import exs.mod.Estudiante;
import exs.mod.Grupo;
import exs.mod.Matricula;
import exs.mod.Tutoria;
import exs.mod.var.Matricula_Var;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin Villalobos A.
 */
public class U_Reg_Mat extends javax.swing.JFrame {

    private ArrayList<Grupo> grupos = null;
    private Estudiante estudiante = null;

    public U_Reg_Mat(Estudiante estudiante) {
        this.estudiante = estudiante;
        initComponents();
        init();
    }

    private void init() {
        this.setTitle("Matrícula de Tutoría - ExS");
        sp_cant.setModel(new SpinnerNumberModel(1, 1, 10, 1));
        l_nrc.setVisible(false);
        setImages();
        fill_combos();
        l_gre.setText("Gracias " + estudiante.getNombre() + " " + estudiante.getPriApellido() + ", ahora complete la información del curso");
        l_gre1.setText("  y seleccione el grupo de tutorías que desea matricular. ");
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);
        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }

    }

    private void fill_combos() {
        ArrayList<Tutoria> tutorias = Gestor_Est.getInstancia()._getTutorias();
        for (int i = 0; i < tutorias.size(); i++) {
            cb_curso.addItem(tutorias.get(i).toString());
        }

    }

    private void send() {
        int selected = table_grupos.getSelectedRow();
        if (cb_curso.getSelectedIndex() > 0 && selected != -1
                && !t_nrc.getText().equals("") && !l_nrc.isVisible()) {
            this.setVisible(false);
            JOptionPane.showMessageDialog(rootPane,
                    "Gracias por registrarse, el comprobante de matrícula y los detalles del curso serán enviados a su correo.",
                    "Matrícula Exitosa", JOptionPane.INFORMATION_MESSAGE);

            Grupo g = grupos.get(selected);
            Tutoria tutoria = Gestor_Est.getInstancia()._getTutorias().get(cb_curso.getSelectedIndex() - 1);
            Gestor_Est.getInstancia().insert_matricula(
                    new Matricula(g.getNum(), estudiante.getId() + "", null, 
                    Matricula_Var.ACTIVO, 0.0f, Integer.parseInt(t_nrc.getText()), (Integer) sp_cant.getValue()),
                    estudiante, g, tutoria);
            close();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe completar todos los espacios en blanco y seleccionar un grupo de la tabla.");
        }
    }

    private void close() {
        dispose();
    }

    private void update_table() {
        int i = cb_curso.getSelectedIndex();
        DefaultTableModel modelo = (DefaultTableModel) table_grupos.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
        if (i > 0) {
            Tutoria tutoria = Gestor_Est.getInstancia()._getTutorias().get(i - 1);
            grupos = Gestor_Est.getInstancia().getGrupos(tutoria.getCod());
            for (int j = 0; grupos != null && j < grupos.size(); j++) {
                Grupo g = grupos.get(j);
                Object[] array = new Object[]{g.getNum(), g._getHorario()};
                modelo.addRow(array);
            }
        } else {
            grupos = null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        b_acep = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_curso = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        sp_cant = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        t_nrc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_grupos = new javax.swing.JTable();
        l_gre = new javax.swing.JLabel();
        l_gre1 = new javax.swing.JLabel();
        l_nrc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(630, 560));

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("Información Académica");

        jSeparator1.setEnabled(false);

        b_acep.setText("Matricular");
        b_acep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_acepActionPerformed(evt);
            }
        });

        b_cancel.setText("Cancelar");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso Matriculado");

        cb_curso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cb_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cursoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de veces matriculado");

        jLabel5.setText("NRC");

        t_nrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chk_nrc(evt);
            }
        });

        jLabel6.setText("Grupo");

        table_grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Horario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_grupos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_grupos);

        l_gre.setText("Nombre");

        l_gre1.setText("Nombre");

        l_nrc.setForeground(new java.awt.Color(153, 0, 0));
        l_nrc.setText("El NRC debe ser únicamente números.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_gre)
                            .addComponent(jLabel1)
                            .addComponent(l_gre1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(83, 83, 83)
                                        .addComponent(t_nrc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sp_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(cb_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(l_nrc)
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_acep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_gre)
                .addGap(3, 3, 3)
                .addComponent(l_gre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sp_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(t_nrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_nrc))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_acep)
                    .addComponent(b_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        close();
    }//GEN-LAST:event_b_cancelActionPerformed

    private void b_acepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_acepActionPerformed
        send();
    }//GEN-LAST:event_b_acepActionPerformed

    private void cb_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cursoActionPerformed
        update_table();
    }//GEN-LAST:event_cb_cursoActionPerformed

    private void chk_nrc(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chk_nrc
        l_nrc.setVisible(!Util.checkIsNumber(t_nrc.getText()));
    }//GEN-LAST:event_chk_nrc
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_acep;
    private javax.swing.JButton b_cancel;
    private javax.swing.JComboBox cb_curso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_gre;
    private javax.swing.JLabel l_gre1;
    private javax.swing.JLabel l_nrc;
    private javax.swing.JSpinner sp_cant;
    private javax.swing.JTextField t_nrc;
    private javax.swing.JTable table_grupos;
    // End of variables declaration//GEN-END:variables
}
