package exs_conncr;

import exs.db.ConnProps;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A
 */
public class Creator extends javax.swing.JFrame {

    /**
     * Creates new form Creator
     */
    public Creator() {
        initComponents();
        setCombos();
    }

    private void setCombos() {
        c_dbg.setSelectedIndex(1);
        t_driver.setText("com.mysql.jdbc.Driver");
        t_url.setText("jdbc:mysql://");
        c_dbg.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                changeDriver();
            }
        });
    }

    private void changeDriver() {
        String dbg = (String) c_dbg.getSelectedItem();
        if (dbg.equals("MYSQL")) {
            t_driver.setText("com.mysql.jdbc.Driver");
            t_url.setText("jdbc:mysql://");
        } else {
            if (dbg.equals("ORACLE")) {
                t_driver.setText("oracle.jdbc.OracleDriver");
                t_url.setText("jdbc:oracle:thin:@");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        c_dbg = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        t_driver = new javax.swing.JTextField();
        t_url = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_db = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        t_ip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        b_save = new javax.swing.JButton();
        t_port = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Conn Creator");

        jLabel2.setText("DB Gestor");

        c_dbg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ORACLE", "MYSQL"}));

        jLabel3.setText("Driver");

        t_driver.setEditable(false);

        t_url.setEditable(false);

        jLabel4.setText("URL");

        jLabel5.setText("DB");

        jLabel7.setText("User");

        jLabel8.setText("Pass");

        jLabel9.setText("IP");

        jLabel10.setText("Port");

        b_save.setText("Guardar");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_save))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_dbg, 0, 145, Short.MAX_VALUE)
                            .addComponent(t_db)
                            .addComponent(t_user)
                            .addComponent(t_ip))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_url)
                            .addComponent(t_driver)
                            .addComponent(t_pass)
                            .addComponent(t_port, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_dbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(t_driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(t_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(b_save)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        if (isFull()) {
            saveProps();
        }
    }//GEN-LAST:event_b_saveActionPerformed

    private boolean isFull() {
        if (t_ip.getText().equals("")
                || t_port.getText().equals("")
                || t_db.getText().equals("")
                || t_user.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe indicar todos los campos anteriores, a execpción de la contraseña si es que tiene", "Form Incompleto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void saveProps() {
        ch.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int w = ch.showSaveDialog(this);
        if (w == JFileChooser.APPROVE_OPTION) {
            String path = ch.getSelectedFile().getAbsolutePath();
            ConnProps conn = getProps();
            if (!path.endsWith(".exs") && !path.endsWith(".EXS")) {
                path += ".exs";
            }
            try {
                FileOutputStream fileOut =
                        new FileOutputStream(path);
                ObjectOutputStream out =
                        new ObjectOutputStream(fileOut);
                out.writeObject(conn);
                out.close();
                fileOut.close();
                JOptionPane.showMessageDialog(rootPane, "El archivo fue guardado con éxito!");
            } catch (IOException i) {
                JOptionPane.showMessageDialog(this, "Compruebe la ruta del archivo que esta guardando y el nombre del archivo!", "Error de escritura", JOptionPane.ERROR_MESSAGE);
                System.err.println(i.getMessage());
            }

        }
    }

    private ConnProps getProps() {
        ConnProps conn = new ConnProps();
        conn.setUrl(t_url.getText());
        conn.setDriver(t_driver.getText());
        conn.setIP(t_ip.getText());
        conn.setPort(t_port.getText());
        conn.setDb(t_db.getText());
        conn.setUser(t_user.getText());
        conn.setPassword(String.valueOf(t_pass.getPassword()));
        return conn;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_save;
    private javax.swing.JComboBox c_dbg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField t_db;
    private javax.swing.JTextField t_driver;
    private javax.swing.JTextField t_ip;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_port;
    private javax.swing.JTextField t_url;
    private javax.swing.JTextField t_user;
    // End of variables declaration//GEN-END:variables
    JFileChooser ch = new JFileChooser();
}
