package View;

import Controller.Gestor;
import exs.logs.err.Log;
import exs.mod.Carrera;
import exs.mod.var.Estudiante_Var;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_New_Carrera extends javax.swing.JFrame {

    private Carrera update = null;
    private int num = 0;

    public Admin_New_Carrera(Carrera t) {
        initComponents();
        update = t;
        this.num = Gestor.getInstancia()._getCarreras(false).size() + 1;
        setImages();
        init();
    }

    private void init() {
        fill_combos_sedes();
        t_num.setEditable(false);
        t_num.setEnabled(false);
        if (update != null) {
            t_num.setText(update.getNum() + "");
            t_nom.setText(update.getNombre());
            cb_sede.setSelectedIndex(update.getSede() + 1);
            this.setTitle("Editar Carrera");
            l_tuto.setText("Modificar Carrera");
            l_text.setText("Ingrese los datos para modificar una carrera y luego presione el botón de Editar.");
            b_add.setText("Editar");
        } else {
            update_num();
            this.setTitle("Nueva Carrera");
        }

    }

    private void update_num() {
        if (!isAvailable(num)) {
            num++;
            update_num();
        } else {
            t_num.setText(num + "");
        }

    }

    private boolean isAvailable(int n) {
        ArrayList<Carrera> carreras = Gestor.getInstancia()._getCarreras(false);
        for (int i = 0; i < carreras.size(); i++) {
            if (n == carreras.get(i).getNum()) {
                return false;
            }
        }
        return true;
    }

    private void fill_combos_sedes() {
        try {
            for (int i = 0; i < Estudiante_Var.SEDES.length; i++) {
                cb_sede.addItem(Estudiante_Var.SEDES[i]);
            }
        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_tuto = new javax.swing.JLabel();
        l_text = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        b_add = new javax.swing.JButton();
        b_can = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_num = new javax.swing.JTextField();
        t_nom = new javax.swing.JTextField();
        l_sede = new javax.swing.JLabel();
        cb_sede = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        l_tuto.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_tuto.setText("Agregar Tutoría");

        l_text.setText("Ingrese los datos para agregar una carrera y luego presione el botón de Agregar.");

        b_add.setText("Agregar");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_can.setText("Cancelar");
        b_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_canActionPerformed(evt);
            }
        });

        jLabel2.setText("Número");

        jLabel3.setText("Nombre");

        l_sede.setText("Sede");

        cb_sede.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_tuto)
                            .addComponent(l_text)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(l_sede))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_num)
                            .addComponent(t_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(cb_sede, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_add)
                .addGap(18, 18, 18)
                .addComponent(b_can)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_sede)
                    .addComponent(cb_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add)
                    .addComponent(b_can))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        send();
    }//GEN-LAST:event_b_addActionPerformed

    private void b_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_canActionPerformed
        close();
    }//GEN-LAST:event_b_canActionPerformed

    private void close() {
        dispose();
    }

    private void send() {
        if (!t_num.getText().equals("") && !t_nom.getText().equals("") && cb_sede.getSelectedIndex() > 0) {
            if (update == null) {
                Gestor.getInstancia().insert_carrera(new Carrera(Integer.parseInt(t_num.getText()), t_nom.getText(), cb_sede.getSelectedIndex() - 1));
            } else {
                update.setNombre(t_nom.getText());
                update.setSede(cb_sede.getSelectedIndex() - 1);
                Gestor.getInstancia().update_carrera(update);
            }
            close();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe completar todos los espacios en blanco.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_can;
    private javax.swing.JComboBox cb_sede;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_sede;
    private javax.swing.JLabel l_text;
    private javax.swing.JLabel l_tuto;
    private javax.swing.JTextField t_nom;
    private javax.swing.JTextField t_num;
    // End of variables declaration//GEN-END:variables
}
