package View;

import Controller.Gestor;
import exs.logs.err.Log;
import exs.mod.Carrera;
import exs.mod.Estudiante;
import exs.mod.Tutor;
import exs.mod.Tutoria;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java_to_excel.Excel;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_Main extends javax.swing.JFrame implements Observer {

    //Gestor
    private Gestor controller = Gestor.getInstancia();
    private static int MIN_H = 600;
    private static int MIN_W = 975;

    public Admin_Main() {
        this.excel=new Excel();
        if (controller.isUsable()) {
            initComponents();
            setImages();
            controller.addObserver(this);
        } else {
            setVisible(false);
            JOptionPane.showMessageDialog(null, "No se puede continuar con la ejecucion del programa...", "DB Error", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);
            l_ima.setIcon(new ImageIcon("img/front_admin.jpg"));
            b_grupo_editar.setIcon(new ImageIcon("img/g_add.png"));
        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
        setImaAdd();
        setImaEdit();
        setImaDel();
        setMaximumSize(new Dimension(MIN_W, MIN_H));
    }

    private void setImaAdd() {
        try {
            String path = "img/b_add.png";
            ImageIcon ima = new ImageIcon(path);
            b_tutor_add.setIcon(ima);
            b_tutoria_add.setIcon(ima);
            b_est_add.setIcon(ima);
            b_carrera_add.setIcon(ima);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
    }

    private void setImaEdit() {
        try {
            String path = "img/b_up.png";
            ImageIcon ima = new ImageIcon(path);
            b_tutor_edit.setIcon(ima);
            b_tutoria_edit.setIcon(ima);
            b_est_edit.setIcon(ima);
            b_carrera_edit.setIcon(ima);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
    }

    private void setImaDel() {
        try {
            String path = "img/b_del.png";
            ImageIcon ima = new ImageIcon(path);
            b_tutor_del.setIcon(ima);
            b_tutoria_del.setIcon(ima);
            b_est_del.setIcon(ima);
            b_carrera_del.setIcon(ima);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
    }

    private void fixIma() {
        l_ima.setLocation((this.getWidth() / 2) - (l_ima.getWidth() / 2), l_ima.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_ima = new javax.swing.JLabel();
        tab_pane = new javax.swing.JTabbedPane();
        p_tutorias = new javax.swing.JPanel();
        scrpane1 = new javax.swing.JScrollPane();
        table_tutorias = new javax.swing.JTable();
        b_tutoria_add = new javax.swing.JButton();
        b_tutoria_edit = new javax.swing.JButton();
        b_tutoria_del = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        p_grupos = new javax.swing.JPanel();
        scrpane2 = new javax.swing.JScrollPane();
        table_grupos = new javax.swing.JTable();
        b_grupo_editar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p_tutores = new javax.swing.JPanel();
        scrpane3 = new javax.swing.JScrollPane();
        table_tutores = new javax.swing.JTable();
        b_tutor_add = new javax.swing.JButton();
        b_tutor_edit = new javax.swing.JButton();
        b_tutor_del = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        p_estudiantes = new javax.swing.JPanel();
        scrpane4 = new javax.swing.JScrollPane();
        table_estudiantes = new javax.swing.JTable();
        b_est_add = new javax.swing.JButton();
        b_est_edit = new javax.swing.JButton();
        b_est_del = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scrpane5 = new javax.swing.JScrollPane();
        table_carreras = new javax.swing.JTable();
        b_carrera_add = new javax.swing.JButton();
        b_carrera_edit = new javax.swing.JButton();
        b_carrera_del = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                Fix_Size(evt);
            }
        });

        tab_pane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab_paneStateChanged(evt);
            }
        });

        table_tutorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_tutorias.getTableHeader().setReorderingAllowed(false);
        scrpane1.setViewportView(table_tutorias);

        b_tutoria_add.setText("Agregar");
        b_tutoria_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutoria_addActionPerformed(evt);
            }
        });

        b_tutoria_edit.setText("  Editar");
        b_tutoria_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutoria_editActionPerformed(evt);
            }
        });

        b_tutoria_del.setText("Borrar");
        b_tutoria_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutoria_delActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        jButton1.setToolTipText("Haga Click Aqui para exportar la Tabla a Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_tutoriasLayout = new javax.swing.GroupLayout(p_tutorias);
        p_tutorias.setLayout(p_tutoriasLayout);
        p_tutoriasLayout.setHorizontalGroup(
            p_tutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tutoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_tutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b_tutoria_add, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(b_tutoria_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_tutoria_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        p_tutoriasLayout.setVerticalGroup(
            p_tutoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tutoriasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(b_tutoria_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_tutoria_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_tutoria_del, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_tutoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_pane.addTab("Tutorías", p_tutorias);

        table_grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad de Grupos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_grupos.getTableHeader().setReorderingAllowed(false);
        scrpane2.setViewportView(table_grupos);

        b_grupo_editar.setText("Editar");
        b_grupo_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_grupo_editarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        jButton2.setToolTipText("Haga Click Aqui para exportar la Tabla a Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_gruposLayout = new javax.swing.GroupLayout(p_grupos);
        p_grupos.setLayout(p_gruposLayout);
        p_gruposLayout.setHorizontalGroup(
            p_gruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_gruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_grupo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        p_gruposLayout.setVerticalGroup(
            p_gruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(p_gruposLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(b_grupo_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_pane.addTab("Grupos", p_grupos);

        table_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Genero", "Nombre", "Télefono", "E-Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_tutores.getTableHeader().setReorderingAllowed(false);
        scrpane3.setViewportView(table_tutores);

        b_tutor_add.setText("Agregar");
        b_tutor_add.setToolTipText("");
        b_tutor_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutor_addActionPerformed(evt);
            }
        });

        b_tutor_edit.setText("  Editar");
        b_tutor_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutor_editActionPerformed(evt);
            }
        });

        b_tutor_del.setText("Borrar");
        b_tutor_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tutor_delActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        jButton3.setToolTipText("Haga Click Aqui para exportar la Tabla a Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_tutoresLayout = new javax.swing.GroupLayout(p_tutores);
        p_tutores.setLayout(p_tutoresLayout);
        p_tutoresLayout.setHorizontalGroup(
            p_tutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_tutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_tutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b_tutor_add, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(b_tutor_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_tutor_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        p_tutoresLayout.setVerticalGroup(
            p_tutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_tutoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(b_tutor_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_tutor_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_tutor_del, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_tutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_pane.addTab("Tutores", p_tutores);

        table_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Genero", "Nombre", "Télefono", "Celular", "E-Mail", "Beca", "Sede", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_estudiantes.getTableHeader().setReorderingAllowed(false);
        scrpane4.setViewportView(table_estudiantes);

        b_est_add.setText("Agregar");
        b_est_add.setToolTipText("");
        b_est_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_est_addActionPerformed(evt);
            }
        });

        b_est_edit.setText("  Editar");
        b_est_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_est_editActionPerformed(evt);
            }
        });

        b_est_del.setText("Borrar");
        b_est_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_est_delActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        jButton4.setToolTipText("Haga Click Aqui para exportar la Tabla a Excel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_estudiantesLayout = new javax.swing.GroupLayout(p_estudiantes);
        p_estudiantes.setLayout(p_estudiantesLayout);
        p_estudiantesLayout.setHorizontalGroup(
            p_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_estudiantesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(scrpane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b_est_add, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(b_est_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_est_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        p_estudiantesLayout.setVerticalGroup(
            p_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_estudiantesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(b_est_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_est_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_est_del, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_estudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        tab_pane.addTab("Estudiantes", p_estudiantes);

        table_carreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Nombre", "Sede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_carreras.getTableHeader().setReorderingAllowed(false);
        scrpane5.setViewportView(table_carreras);

        b_carrera_add.setText("Agregar");
        b_carrera_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_carrera_addActionPerformed(evt);
            }
        });

        b_carrera_edit.setText("  Editar");
        b_carrera_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_carrera_editActionPerformed(evt);
            }
        });

        b_carrera_del.setText("Borrar");
        b_carrera_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_carrera_delActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        jButton5.setToolTipText("Haga Click Aqui para exportar la Tabla a Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b_carrera_add, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(b_carrera_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_carrera_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(b_carrera_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_carrera_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_carrera_del, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpane5, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_pane.addTab("Carreras", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_pane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(l_ima, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_ima, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_pane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_grupo_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_grupo_editarActionPerformed
        int i = table_grupos.getSelectedRow();
        if (i >= 0) {
            Tutoria t = controller.getTutorias().get(i);
            new Admin_Grupos(t).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero una tutoría de la tabla");
        }
    }//GEN-LAST:event_b_grupo_editarActionPerformed

    private void tab_paneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab_paneStateChanged
        update_tables();
    }//GEN-LAST:event_tab_paneStateChanged

    private void Fix_Size(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Fix_Size
        if (getWidth() < MIN_W) {
            setSize(MIN_H, getHeight());
        }
        if (getHeight() < MIN_H) {
            setSize(getWidth(), MIN_H);
        }
        fixIma();
    }//GEN-LAST:event_Fix_Size

    private void b_tutoria_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutoria_delActionPerformed
        del_tutoria();
    }//GEN-LAST:event_b_tutoria_delActionPerformed

    private void b_tutoria_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutoria_addActionPerformed
        new Admin_New_Tutoria(null).setVisible(true);
    }//GEN-LAST:event_b_tutoria_addActionPerformed

    private void b_tutoria_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutoria_editActionPerformed
        int i = table_tutorias.getSelectedRow();
        if (i >= 0) {
            Tutoria t = controller._getTutorias().get(i);
            new Admin_New_Tutoria(t).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero una tutoría de la tabla");
        }
    }//GEN-LAST:event_b_tutoria_editActionPerformed

    private void b_tutor_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutor_addActionPerformed
        new Admin_New_Tutor(null).setVisible(true);
    }//GEN-LAST:event_b_tutor_addActionPerformed

    private void b_tutor_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutor_editActionPerformed
        int i = table_tutores.getSelectedRow();
        if (i >= 0) {
            Tutor t = controller._getTutores().get(i);
            new Admin_New_Tutor(t).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un tutor de la tabla");
        }
    }//GEN-LAST:event_b_tutor_editActionPerformed

    private void b_tutor_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tutor_delActionPerformed
        del_tutor();
    }//GEN-LAST:event_b_tutor_delActionPerformed

    private void b_est_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_est_addActionPerformed
        new Admin_New_Est(null).setVisible(true);
    }//GEN-LAST:event_b_est_addActionPerformed

    private void b_est_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_est_editActionPerformed
        int i = table_estudiantes.getSelectedRow();
        if (i >= 0) {
            Estudiante estudiante = controller._getEstudiantes().get(i);
            new Admin_New_Est(estudiante).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un estudiante de la tabla");
        }
    }//GEN-LAST:event_b_est_editActionPerformed

    private void b_est_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_est_delActionPerformed
        int i = table_estudiantes.getSelectedRow();
        if (i >= 0) {
            Estudiante t = controller._getEstudiantes().get(i);
            String msj = "Seguro que desea borrar ";
            msj += (t.getGenero() == 1) ? "el estudiante " : "la estudiante ";
            msj += t.getId() + " - " + t.getNombre() + " " + t.getPriApellido() + " " + t.getSegApellido() + "?";
            int r = JOptionPane.showConfirmDialog(rootPane, msj, "Borrar Estudiante", JOptionPane.YES_NO_OPTION);
            if (r == 0) {
                controller.del_estudiante(i);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un estudiante de la tabla");
        }
    }//GEN-LAST:event_b_est_delActionPerformed

    private void b_carrera_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_carrera_addActionPerformed
        new Admin_New_Carrera(null).setVisible(true);
    }//GEN-LAST:event_b_carrera_addActionPerformed

    private void b_carrera_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_carrera_editActionPerformed
        int i = table_carreras.getSelectedRow();
        if (i >= 0) {
            Carrera t = controller._getCarreras(false).get(i);
            new Admin_New_Carrera(t).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero una carrera de la tabla");
        }
    }//GEN-LAST:event_b_carrera_editActionPerformed

    private void b_carrera_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_carrera_delActionPerformed
        int i = table_carreras.getSelectedRow();
        if (i >= 0) {
            Carrera t = controller._getCarreras(false).get(i);
            String msj = "Seguro que desea borrar la carrera " + t.toString() + "?";
            int r = JOptionPane.showConfirmDialog(rootPane, msj, "Borrar Carrera", JOptionPane.YES_NO_OPTION);
            if (r == 0) {
                controller.del_carrera(i);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero una carrera de la tabla");
        }
    }//GEN-LAST:event_b_carrera_delActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.guardarCarrerasExcel();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.guardarEstudiantesExcel();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.guardarTutoresExcel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.guardarGruposExcel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.guardarTutoriasExcel();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void del_tutoria() {
        int i = table_tutorias.getSelectedRow();
        if (i >= 0) {
            Tutoria t = controller._getTutorias().get(i);
            String msj = "Seguro que desea borrar la tutoría " + t.getCod() + " " + t.getNom() + "?";
            int r = JOptionPane.showConfirmDialog(rootPane, msj, "Borrar Tutoría", JOptionPane.YES_NO_OPTION);
            if (r == 0) {
                controller.del_tutoria(i);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero una tutoría de la tabla");
        }
    }

    public void del_tutor() {
        int i = table_tutores.getSelectedRow();
        if (i >= 0) {
            Tutor t = controller._getTutores().get(i);
            String msj = "Seguro que desea borrar ";
            msj += (t.getGenero() == 1) ? "el tutor " : "la tutora ";
            msj += t.getId() + " - " + t.getNombre() + " " + t.getPriApellido() + " " + t.getSegApellido() + "?";
            int r = JOptionPane.showConfirmDialog(rootPane, msj, "Borrar Tutor", JOptionPane.YES_NO_OPTION);
            if (r == 0) {
                controller.del_tutor(i);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un tutor de la tabla");
        }
    }

    private void update_tables() {

        int i = tab_pane.getSelectedIndex();
        switch (i) {
            case 0:
                fillTable_Tutorias();
                break;
            case 1:
                fillTable_Grupos();
                break;
            case 2:
                fillTable_Tutores();
                break;
            case 3:
                fillTable_Estudiantes();
                break;

            case 4:
                fillTable_Carreras();
                break;

        }
        fixIma();
    }

    private void fillTable_Carreras() {
        this.setTitle("Carreras  -  ExS");
        limpiaTabla(table_carreras);
        ArrayList<Carrera> list = controller.getCarreras(false);
        DefaultTableModel modelo = (DefaultTableModel) table_carreras.getModel();
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(list.get(i).toArray());
        }
    }

    private void fillTable_Estudiantes() {
        this.setTitle("Estudiantes  -  ExS");
        limpiaTabla(table_estudiantes);
        ArrayList<Estudiante> list = controller.getEstudiantes();
        DefaultTableModel modelo = (DefaultTableModel) table_estudiantes.getModel();
        for (int i = 0; i < list.size(); i++) {
            Object[] array = list.get(i).toArray();
            array[8] = controller.getCarrera(Integer.parseInt((String) array[8]));
            modelo.addRow(array);
        }
    }

    private void fillTable_Tutores() {
        this.setTitle("Tutores  -  ExS");
        limpiaTabla(table_tutores);
        ArrayList<Tutor> list = controller.getTutores();
        DefaultTableModel modelo = (DefaultTableModel) table_tutores.getModel();
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(list.get(i).toArray());
        }
    }

    private void fillTable_Tutorias() {
        this.setTitle("Tutorías  -  ExS");
        limpiaTabla(table_tutorias);
        ArrayList<Tutoria> list = controller.getTutorias();
        DefaultTableModel modelo = (DefaultTableModel) table_tutorias.getModel();
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(list.get(i).toArray());
        }
    }

    private void limpiaTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
    }

    private void fillTable_Grupos() {
        this.setTitle("Grupos  -  ExS");
        limpiaTabla(table_grupos);
        ArrayList<Tutoria> list = controller.getTutorias();
        DefaultTableModel modelo = (DefaultTableModel) table_grupos.getModel();
        for (int i = 0; i < list.size(); i++) {
            Object[] array = new Object[3];
            array[0] = list.get(i).getCod();
            array[1] = list.get(i).getNom();
            array[2] = controller.getCantidadGrupos(list.get(i).getCod());
            modelo.addRow(array);
        }

    }

    private void fillTable_() {

        JOptionPane.showMessageDialog(rootPane, "Se actualiza table OTRO!!");
    }
    
    Excel excel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_carrera_add;
    private javax.swing.JButton b_carrera_del;
    private javax.swing.JButton b_carrera_edit;
    private javax.swing.JButton b_est_add;
    private javax.swing.JButton b_est_del;
    private javax.swing.JButton b_est_edit;
    private javax.swing.JButton b_grupo_editar;
    private javax.swing.JButton b_tutor_add;
    private javax.swing.JButton b_tutor_del;
    private javax.swing.JButton b_tutor_edit;
    private javax.swing.JButton b_tutoria_add;
    private javax.swing.JButton b_tutoria_del;
    private javax.swing.JButton b_tutoria_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_ima;
    private javax.swing.JPanel p_estudiantes;
    private javax.swing.JPanel p_grupos;
    private javax.swing.JPanel p_tutores;
    private javax.swing.JPanel p_tutorias;
    private javax.swing.JScrollPane scrpane1;
    private javax.swing.JScrollPane scrpane2;
    private javax.swing.JScrollPane scrpane3;
    private javax.swing.JScrollPane scrpane4;
    private javax.swing.JScrollPane scrpane5;
    private javax.swing.JTabbedPane tab_pane;
    private javax.swing.JTable table_carreras;
    private javax.swing.JTable table_estudiantes;
    private javax.swing.JTable table_grupos;
    private javax.swing.JTable table_tutores;
    private javax.swing.JTable table_tutorias;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        update_tables();
    }
    
        private void guardarCarrerasExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_carreras,path);
    }
       
   private void guardarEstudiantesExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_estudiantes,path);
    }  
   
   private void guardarGruposExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_grupos,path);
    }
   
   private void guardarTutoresExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_tutores,path);
    }
   
   private void guardarTutoriasExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_tutorias,path);
    }
}
	