package View;

import Controller.Gestor;
import exs.logs.err.Log;
import exs.mod.Estudiante;
import exs.mod.Tutor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_Select_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Select_Tutor
     */
    private int seleccion = -1;
    private boolean change = false;

    public Admin_Select_Estudiante() {
        initComponents();
        setImages();
    }

    public void setChange(boolean change) {
        this.change = change;
    }

    public boolean isChange() {
        return change;
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);
            this.setTitle("Seleccione un tutor...");
        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }

    }

    public void update_table() {
        limpiaTabla(table_estudiante);
        ArrayList<Estudiante> list = Gestor.getInstancia().getEstudiantes();
        DefaultTableModel modelo = (DefaultTableModel) table_estudiante.getModel();
        for (int i = 0; i < list.size(); i++) {
            Estudiante e = list.get(i);
            Object[] array = new Object[]{e.getId(), e.getNombre() + " " + e.getPriApellido() + " " + e.getSegApellido().charAt(0)};
            modelo.addRow(array);
        }

    }

    private void limpiaTabla(JTable tabla) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }
    }

    public int getSeleccion() {
        return seleccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_estudiante = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        b_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        table_estudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_estudiante.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_estudiante);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel(evt);
            }
        });

        b_add.setText("Seleccionar");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(b_add))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel
        setVisible(false);
    }//GEN-LAST:event_cancel

    private void select(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select
        seleccion = table_estudiante.getSelectedRow();
        if (seleccion >= 0) {
            change = true;
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un tutor de la tabla");
        }
    }//GEN-LAST:event_select
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_estudiante;
    // End of variables declaration//GEN-END:variables
}
