package View;

import Controller.Gestor;
import View.Util.Util;
import exs.logs.err.Log;
import exs.mod.Carrera;
import exs.mod.Estudiante;
import exs.mod.var.Estudiante_Var;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_New_Est extends javax.swing.JFrame {

    private Estudiante update = null;
    private ArrayList<Carrera> carreras_sede = null;

    /**
     * Creates new form U_Reg_Per_Info
     */
    public Admin_New_Est(Estudiante e) {
        initComponents();
        update = e;
        fill_combos();
        init();
        setImages();

    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }

    }

    private void init() {
        l_id.setVisible(false);
        l_id_av.setVisible(false);
        l_email.setVisible(false);
        l_cel.setVisible(false);
        l_tel.setVisible(false);
        if (update != null) {
            t_id.setEditable(false);
            t_id.setEnabled(false);
            t_id.setText("" + update.getId());
            t_name.setText(update.getNombre());
            t_pname.setText(update.getPriApellido());
            t_sname.setText(update.getSegApellido());
            t_cel.setText("" + update.getCelular());
            t_tel.setText("" + update.getTelefono());
            t_email.setText(update.getEmail());
            cb_beca.setSelectedIndex(update.getBeca());
            cb_sede.setSelectedIndex(update.getSede()+1);
            update_combos();
            select_carrera(update.getCarrera());
            if (update.getGenero() == 1) {
                r_masc.setSelected(true);
            } else {
                if (update.getGenero() == 2) {
                    r_fem.setSelected(true);
                }
            }
            this.setTitle("Editar Estudiante");
            l_tuto.setText("Modificar Estudiante");
            l_text.setText("Ingrese los datos para modificar un estudiante y luego presione el botón de Editar.");
            b_add.setText("Editar");
        } else {
            this.setTitle("Nuevo Estudiante");
        }
    }

    private void fill_combos() {
        cb_carrera.setEnabled(false);
        for (int i = 0; i < Estudiante_Var.SEDES.length; i++) {
            cb_sede.addItem(Estudiante_Var.getSede(i));
        }
        for (int i = 0; i < Estudiante_Var.BECAS.length; i++) {
            cb_beca.addItem(Estudiante_Var.getBeca(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_cel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        r_fem = new javax.swing.JRadioButton();
        r_masc = new javax.swing.JRadioButton();
        l_tuto = new javax.swing.JLabel();
        l_text = new javax.swing.JLabel();
        b_add = new javax.swing.JButton();
        b_can = new javax.swing.JButton();
        l_id = new javax.swing.JLabel();
        l_cel = new javax.swing.JLabel();
        l_tel = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        l_id_av = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb_beca = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cb_sede = new javax.swing.JComboBox();
        cb_carrera = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        setResizable(false);

        jSeparator1.setEnabled(false);

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        t_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_Id(evt);
            }
        });

        jLabel5.setText("Identificación");

        jLabel6.setText("Teléfono Celular");

        t_cel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_Cel(evt);
            }
        });

        jLabel7.setText("Teléfono Domicilio");

        t_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_Tel(evt);
            }
        });

        jLabel8.setText("E-Mail");

        t_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_Email(evt);
            }
        });

        jLabel9.setText("Género");

        buttonGroup1.add(r_fem);
        r_fem.setText("Femenino");

        buttonGroup1.add(r_masc);
        r_masc.setText("Masculino");

        l_tuto.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_tuto.setText("Agregar Estudiante");

        l_text.setText("Ingrese los datos para agregar un Estudiante y luego presione el botón de Agregar.");

        b_add.setText("Agregar");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_can.setText("Cancelar");
        b_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_canActionPerformed(evt);
            }
        });

        l_id.setForeground(new java.awt.Color(153, 0, 0));
        l_id.setText("Deben ser sólo números");

        l_cel.setForeground(new java.awt.Color(153, 0, 0));
        l_cel.setText("Celular inválido, deben ser sólo númenos.");

        l_tel.setForeground(new java.awt.Color(153, 0, 0));
        l_tel.setText("Teléfono inválido, deben ser sólo númenos.");

        l_email.setForeground(new java.awt.Color(153, 0, 0));
        l_email.setText("E-Mail inválido.");

        l_id_av.setForeground(new java.awt.Color(153, 0, 0));
        l_id_av.setText("X");

        jLabel1.setText("Beca");

        cb_beca.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));

        jLabel10.setText("Sede");

        cb_sede.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "--" }));
        cb_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sedeActionPerformed(evt);
            }
        });

        cb_carrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        jLabel11.setText("Carrera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_tuto)
                            .addComponent(l_text)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_add)
                                .addGap(18, 18, 18)
                                .addComponent(b_can))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(t_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(t_name)
                                                .addComponent(t_pname)
                                                .addComponent(t_cel))
                                            .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(l_cel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_email, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(cb_beca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_id_av, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r_fem)
                                            .addComponent(r_masc))
                                        .addGap(79, 79, 79))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(21, 21, 21)
                                        .addComponent(t_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(t_tel))
                                    .addComponent(l_tel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(l_tuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_id_av))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_id))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_masc)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r_fem))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(t_sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(t_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_tel)
                    .addComponent(l_cel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_beca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add)
                    .addComponent(b_can))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        send();
    }//GEN-LAST:event_b_addActionPerformed

    private void b_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_canActionPerformed
        close();
    }//GEN-LAST:event_b_canActionPerformed

    private void close() {
        dispose();
    }

    private void update_combos() {
        if (cb_sede.getSelectedIndex() <= 0) {
            cb_carrera.setEnabled(false);
        } else {
            cb_carrera.setEnabled(true);
            int sede = cb_sede.getSelectedIndex() - 1;
            carreras_sede = Gestor.getInstancia().getCarreras_Sede(sede);
            cb_carrera.removeAllItems();
            cb_carrera.addItem("--");
            for (int i = 0; i < carreras_sede.size(); i++) {
                cb_carrera.addItem(carreras_sede.get(i).getNombre());
            }
        }
    }

    private void select_carrera(int carrera_num) {
        for (int i = 0; i < carreras_sede.size(); i++) {
            if (carreras_sede.get(i).getNum() == carrera_num) {
                cb_carrera.setSelectedIndex(i + 1);
                return;
            }
        }
    }

    private boolean isSelected() {
        if (r_masc.isSelected() || r_fem.isSelected()) {
            return true;
        }
        return false;
    }

    private void send() {
        if (!t_id.getText().equals("") && !t_name.getText().equals("")
                && !t_pname.getText().equals("") && !t_sname.getText().equals("")
                && !t_cel.getText().equals("") && !t_email.getText().equals("")
                && !t_tel.getText().equals("") && isSelected()) {
            if (!l_id.isVisible() && !l_email.isVisible() && !l_tel.isVisible()
                    && cb_sede.getSelectedIndex() > 0 && cb_carrera.getSelectedIndex() > 0) {
                int gen, cel, tel, id, sede, carrera, beca;
                gen = (r_masc.isSelected()) ? 1 : 2;
                cel = Integer.parseInt(t_cel.getText());
                tel = Integer.parseInt(t_tel.getText());
                beca = cb_beca.getSelectedIndex();
                sede = cb_sede.getSelectedIndex() - 1;
                carrera = carreras_sede.get(cb_carrera.getSelectedIndex() - 1).getNum();
                if (update == null) {

                    if (!l_id_av.isVisible()) {

                        id = Integer.parseInt(t_id.getText());
                        Gestor.getInstancia().insert_estudiante(new Estudiante(t_name.getText(), t_pname.getText(), t_sname.getText(),
                                id, cel, tel, t_email.getText(), gen, beca, sede, carrera));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "La identificación indicada ya se encuentra utilizada por otro tutor.");
                        return;
                    }
                } else {
                    update.setNombre(t_name.getText());
                    update.setPriApellido(t_pname.getText());
                    update.setSegApellido(t_sname.getText());
                    update.setEmail(t_email.getText());
                    update.setGenero(gen);
                    update.setTelefono(tel);
                    update.setCelular(cel);
                    update.setSede(sede);
                    update.setCarrera(carrera);
                    update.setBeca(beca);

                    Gestor.getInstancia().update_estudiante(update);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Verifique el formato de los datos indicados..");
                return;
            }
            close();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe completar todos los espacios en blanco.");
        }
    }

    private void key_Id(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_Id
        String id = t_id.getText();
        l_id.setVisible(!Util.checkIsNumber(id));
        l_id_av.setVisible(Gestor.getInstancia().getEstudiante(id) != null);
    }//GEN-LAST:event_key_Id

    private void key_Email(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_Email
        l_email.setVisible(!Util.checkMail((t_email.getText())));
    }//GEN-LAST:event_key_Email

    private void key_Cel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_Cel
        String cel = t_cel.getText();
        l_cel.setVisible(!Util.checkIsNumber(cel));
    }//GEN-LAST:event_key_Cel

    private void key_Tel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_Tel
        String tel = t_tel.getText();
        l_tel.setVisible(!Util.checkIsNumber(tel));
    }//GEN-LAST:event_key_Tel

    private void cb_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sedeActionPerformed
        update_combos();
    }//GEN-LAST:event_cb_sedeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_can;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb_beca;
    private javax.swing.JComboBox cb_carrera;
    private javax.swing.JComboBox cb_sede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_cel;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_id;
    private javax.swing.JLabel l_id_av;
    private javax.swing.JLabel l_tel;
    private javax.swing.JLabel l_text;
    private javax.swing.JLabel l_tuto;
    private javax.swing.JRadioButton r_fem;
    private javax.swing.JRadioButton r_masc;
    private javax.swing.JTextField t_cel;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_pname;
    private javax.swing.JTextField t_sname;
    private javax.swing.JTextField t_tel;
    // End of variables declaration//GEN-END:variables
}
