package View;

import Controller.Gestor;
import exs.logs.err.Log;
import exs.mod.Tutoria;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_New_Tutoria extends javax.swing.JFrame {

    Tutoria update = null;
    int contNom=30;

    public Admin_New_Tutoria(Tutoria t) {
        initComponents();        
        update = t;        
        setImages();
        init();
    }
    
    private void init(){
        l_av.setVisible(false);
        if (update != null) {
            t_cod.setEditable(false);
            t_cod.setEnabled(false);
            t_cod.setText(update.getCod());
            t_nom.setText(update.getNom());
            this.setTitle("Editar Tutoría");
            l_tuto.setText("Modificar Tutoría");
            l_text.setText("Ingrese los datos para modificar una tutoría y luego presione el botón de Editar.");
            b_add.setText("Editar");
        } else {
            this.setTitle("Nueva Tutoría");
        }
    }

    private void setImages() {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("img/elogo.png"));
            this.setIconImage(img);

        } catch (Exception e) {
            Log.SendLog(e.getMessage());
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_tuto = new javax.swing.JLabel();
        l_text = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        b_add = new javax.swing.JButton();
        b_can = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_cod = new javax.swing.JTextField();
        t_nom = new javax.swing.JTextField();
        l_av = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        l_tuto.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_tuto.setText("Agregar Tutoría");

        l_text.setText("Ingrese los datos para agregar una tutoría y luego presione el botón de Agregar.");

        b_add.setText("Agregar");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_can.setText("Cancelar");
        b_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_canActionPerformed(evt);
            }
        });

        jLabel2.setText("Código");

        jLabel3.setText("Nombre");

        t_cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                look_cod(evt);
            }
        });

        t_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nomKeyTyped(evt);
            }
        });

        l_av.setForeground(new java.awt.Color(153, 0, 0));
        l_av.setText("Código no disponible");

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Maximo 15 caracteres");

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Maximo 30 caracteres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_tuto)
                            .addComponent(l_text)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_cod)
                                .addComponent(t_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(l_av)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_add)
                .addGap(18, 18, 18)
                .addComponent(b_can)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_av))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add)
                    .addComponent(b_can))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        send();
    }//GEN-LAST:event_b_addActionPerformed

    private void b_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_canActionPerformed
        close();
    }//GEN-LAST:event_b_canActionPerformed

    private void look_cod(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_look_cod
        l_av.setVisible(Gestor.getInstancia().is_Cod_Used(t_cod.getText()));
    }//GEN-LAST:event_look_cod

    private void t_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nomKeyTyped
       
    }//GEN-LAST:event_t_nomKeyTyped

    private void close() {
        dispose();
    }

    private void send() {
        if (!t_cod.getText().equals("") && !t_nom.getText().equals("")) {
            if (update == null) {
                if (!l_av.isVisible()) {
                    Gestor.getInstancia().insert_tutoria(new Tutoria(t_cod.getText(), t_nom.getText()));
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El código indicado ya se encuentra utilizado por otra  tutoría.");
                    return;
                }
            } else {
                update.setNom(t_nom.getText());
                Gestor.getInstancia().update_tutoria(update);
            }
            close();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe completar todos los espacios en blanco.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_can;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_av;
    private javax.swing.JLabel l_text;
    private javax.swing.JLabel l_tuto;
    private javax.swing.JTextField t_cod;
    private javax.swing.JTextField t_nom;
    // End of variables declaration//GEN-END:variables
}
