package View;

import Controller.Gestor;
import exs.mod.Estudiante;
import exs.mod.Retirado;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java_to_excel.Excel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Retiraron extends javax.swing.JFrame implements Observer {

    //Attributes
    private Gestor controller = null;
    private ArrayList<Retirado> retirados = null;
    
    public Retiraron() {
        excel=new Excel();
            this.controller = Gestor.getInstancia();
            initComponents();
            Gestor.getInstancia().addObserver(this);
            this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    super.windowClosing(e);
                    close();
                }
            });
            update_table(true);
            setVisible(true);
    }

    private void close() {
        Gestor.getInstancia().deleteObserver(this);
        dispose();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_tuto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrpane1 = new javax.swing.JScrollPane();
        table_estudiantes = new javax.swing.JTable();
        BotonExcel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                fix_Size(evt);
            }
        });

        l_tuto.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_tuto.setText("Estudiantes que Retiraron Cursos");

        table_estudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Celular", "Fecha de Matricula", "Fecha de Retiro", "Curso", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_estudiantes.getTableHeader().setReorderingAllowed(false);
        scrpane1.setViewportView(table_estudiantes);

        BotonExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page_white_excel.png"))); // NOI18N
        BotonExcel.setToolTipText("Haga Click aqui para exportar la tabla a Excel");
        BotonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExcelActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Estudiante");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_tuto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrpane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(BotonExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fix_Size(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_fix_Size
        if (getWidth() < 850) {
            setSize(850, getHeight());
        }
        if (getHeight() < 515) {
            setSize(getWidth(), 515);
        }
    }//GEN-LAST:event_fix_Size

    private void BotonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExcelActionPerformed
        this.guardarGrupoExcel();
    }//GEN-LAST:event_BotonExcelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = this.table_estudiantes.getSelectedRow();        
        if (i >= 0) {
            String cedu=table_estudiantes.getModel().getValueAt(table_estudiantes.getSelectedRow(),0)+"";
            
            Estudiante estudiante = controller.getEstudiante(cedu);
            new Admin_New_Est(estudiante).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar primero un estudiante de la tabla");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    
    

    private void update_table(boolean query) {
        if (query) {
            if (retirados != null) {
                retirados.clear();
            }
            retirados = controller.getRetiraron();

        }

        DefaultTableModel modelo = (DefaultTableModel) table_estudiantes.getModel();
        while (modelo.getRowCount() != 0) {
            modelo.removeRow(0);
        }

      
        for (int i = 0; retirados != null && i < retirados.size(); i++) {
            Retirado m = retirados.get(i);
            Object[] array = new Object[7];
            array[0] = m.getId();
             array[1]=       m.getNombre().toString();
             array[2] = m.getCelular();
            array[3] = m.getFechaMatricula().toString();            
            array[4] = m.getFechaRetiro();
            array[5] = m.getCurso();
            array[6] = m.getMotivo();
            modelo.addRow(array);
        }
    }
    
    Excel excel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonExcel;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_tuto;
    private javax.swing.JScrollPane scrpane1;
    private javax.swing.JTable table_estudiantes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        update_table(true);
    }
    
     private void guardarGrupoExcel() {
       Jfc j=new Jfc();
       String path=j.guardar();
       if(path!=null)
        excel.guardar(table_estudiantes,path);
    }
}
