package View;

import Controller.Gestor;
import View.Util.Util;
import exs.mod.Tutor;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Villalobos A.
 */
public class Admin_New_Tutor extends javax.swing.JFrame {

    private Tutor update = null;

    /**
     * Creates new form Admin_New_Tutor
     */
    public Admin_New_Tutor(Tutor t) {
        initComponents();
        l_id.setVisible(false);
        l_id_av.setVisible(false);
        l_tel.setVisible(false);
        l_mail.setVisible(false);
        update = t;
        if (update != null) {
            t_id.setEditable(false);
            t_id.setEnabled(false);
            t_id.setText("" + t.getId());
            t_name.setText(t.getNombre());
            t_pname.setText(t.getPriApellido());
            t_sname.setText(t.getSegApellido());
            t_cel.setText("" + t.getTelefono());
            t_email.setText(t.getEmail());
            if (t.getGenero() == 1) {
                r_masc.setSelected(true);
            } else {
                if (t.getGenero() == 2) {
                    r_fem.setSelected(true);
                }
            }
            this.setTitle("Editar Tutor");
            l_tuto.setText("Modificar Tutor");
            l_text.setText("Ingrese los datos para modificar un tutor y luego presione el botón de Editar.");
            b_add.setText("Editar");
        } else {
            this.setTitle("Nuevo Tutor");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l_tuto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        r_fem = new javax.swing.JRadioButton();
        r_masc = new javax.swing.JRadioButton();
        b_add = new javax.swing.JButton();
        b_can = new javax.swing.JButton();
        l_text = new javax.swing.JLabel();
        l_id_av = new javax.swing.JLabel();
        l_tel = new javax.swing.JLabel();
        l_mail = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        t_cel = new javax.swing.JTextField();
        t_pname = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        setResizable(false);

        l_tuto.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        l_tuto.setText("Nuevo Tutor");

        jSeparator1.setEnabled(false);

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("ID");

        jLabel6.setText("Teléfono");

        jLabel8.setText("E-Mail");

        t_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chk_mail(evt);
            }
        });

        jLabel9.setText("Género");

        buttonGroup1.add(r_fem);
        r_fem.setText("Femenino");

        buttonGroup1.add(r_masc);
        r_masc.setText("Masculino");

        b_add.setText("Agregar");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_can.setText("Cancelar");
        b_can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_canActionPerformed(evt);
            }
        });

        l_text.setText("Ingrese los datos para agregar un tutor y luego presione el botón de Agregar.");

        l_id_av.setForeground(new java.awt.Color(153, 0, 0));
        l_id_av.setText("Identificación no disponible");

        l_tel.setForeground(new java.awt.Color(153, 0, 0));
        l_tel.setText("Teléfono inválido, deben ser sólo númenos.");

        l_mail.setForeground(new java.awt.Color(153, 0, 0));
        l_mail.setText("E-Mail inválido.");

        l_id.setForeground(new java.awt.Color(153, 0, 0));
        l_id.setText("Identificación inválida, deben ser sólo númenos.");

        t_cel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chk_tel(evt);
            }
        });

        t_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chk_id(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_text)
                                    .addComponent(l_tuto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(t_pname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                    .addComponent(t_cel)
                                                    .addComponent(t_id))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel8)))
                                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l_tel)
                                            .addComponent(l_id)
                                            .addComponent(l_id_av, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(117, 117, 117)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(r_fem)
                                        .addComponent(r_masc)
                                        .addComponent(t_email, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(t_sname)))))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_add)
                        .addGap(18, 18, 18)
                        .addComponent(b_can)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_tuto)
                .addGap(3, 3, 3)
                .addComponent(l_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_masc)
                            .addComponent(jLabel9)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(l_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(r_fem)
                                    .addComponent(l_id_av))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(t_sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t_pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(t_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_mail)
                    .addComponent(l_tel))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_can)
                    .addComponent(b_add))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        send();
    }//GEN-LAST:event_b_addActionPerformed

    private void b_canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_canActionPerformed
        close();
    }//GEN-LAST:event_b_canActionPerformed

    private void chk_mail(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chk_mail
        l_mail.setVisible(!Util.checkMail(t_email.getText()));
    }//GEN-LAST:event_chk_mail

    private void chk_id(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chk_id
        String id = t_id.getText();
        l_id.setVisible(!Util.checkIsNumber(id));
        l_id_av.setVisible(Gestor.getInstancia().getTutor(id) != null);
    }//GEN-LAST:event_chk_id

    private void chk_tel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chk_tel
        String tel = t_cel.getText();
        l_tel.setVisible(!Util.checkIsNumber(tel));
    }//GEN-LAST:event_chk_tel

    private void close() {
        dispose();
    }

    private boolean isSelected() {
        if (r_masc.isSelected() || r_fem.isSelected()) {
            return true;
        }
        return false;
    }

    private void send() {
        if (!t_id.getText().equals("") && !t_name.getText().equals("")
                && !t_pname.getText().equals("") && !t_sname.getText().equals("")
                && !t_cel.getText().equals("") && !t_email.getText().equals("")
                && isSelected()) {
            if (!l_id.isVisible() && !l_mail.isVisible() && !l_tel.isVisible()) {
                if (update == null) {
                    if (!l_id_av.isVisible()) {
                        int gen, cel, id;
                        gen = (r_masc.isSelected()) ? 1 : 2;
                        cel = Integer.parseInt(t_cel.getText());
                        id = Integer.parseInt(t_id.getText());
                        Gestor.getInstancia().insert_tutor(new Tutor(t_name.getText(), t_pname.getText(), t_sname.getText(),
                                id, cel, t_email.getText(), gen));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "La identificación indicada ya se encuentra utilizada por otro tutor.");
                        return;
                    }
                } else {
                    int gen, cel;
                    gen = (r_masc.isSelected()) ? 1 : 2;
                    cel = Integer.parseInt(t_cel.getText());
                    update.setNombre(t_name.getText());
                    update.setPriApellido(t_pname.getText());
                    update.setSegApellido(t_sname.getText());
                    update.setEmail(t_email.getText());
                    update.setGenero(gen);
                    update.setTelefono(cel);
                    Gestor.getInstancia().update_tutor(update);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Verifique el formato de los datos indicados..");
                return;
            }
            close();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe completar todos los espacios en blanco.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_can;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_id;
    private javax.swing.JLabel l_id_av;
    private javax.swing.JLabel l_mail;
    private javax.swing.JLabel l_tel;
    private javax.swing.JLabel l_text;
    private javax.swing.JLabel l_tuto;
    private javax.swing.JRadioButton r_fem;
    private javax.swing.JRadioButton r_masc;
    private javax.swing.JTextField t_cel;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_pname;
    private javax.swing.JTextField t_sname;
    // End of variables declaration//GEN-END:variables
}
